### ISSUE TITLE
Post installation step - Load ANAEE basic data 

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/C195-azure-workspace#12]
The idea is that as part of the installation we should have an OPTIONAL step for loading automatically the initial information provided for the ANAEE use case.

**Comment by etj** [comment]
There are scripts and fixtures at 
https://github.com/geosolutions-it/C195-azure-workspace/tree/master/data

**Comment by lpasquali** [comment]
pushed first commits, I have finish to polish and test the script but it looks like to work

**Comment by lpasquali** [comment]
@etj can we close this?
