### ISSUE TITLE
Post installation step - Automated Smoke testing

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/C195-azure-workspace#13]
What should be checked at application stack startup:

- test ckan is responding
- test redis is working (authentication needed)
- test solr is working (no auth should be needed)
- run some ckan requests with apykey the same way is used in data provisioning script

**Comment by randomorder** [comment]
can you please add a description @lpasquali and provide a concise plan for the implementation and an estimate?

**Comment by lpasquali** [comment]
@randomorder after what we said last friday about Jmeter, I would endorse the use of 4 simple curl for this specific job and analyze the result

**Comment by randomorder** [comment]
Bash script then? Will it be executed automatically by the installation procedure?
let us know what kind of requests, against which services and what components you are testing and the estimate for the implementation

**Comment by lpasquali** [comment]
> Bash script then? Will it be executed automatically by the installation procedure?
> let us know what kind of requests, against which services and what components you are testing and the estimate for the implementation

@randomorder

**Comment by lpasquali** [comment]
@randomorder I would make it a script to be called after ckan has finished coming up

**Comment by randomorder** [comment]
> > Bash script then? Will it be executed automatically by the installation procedure?
> > let us know what kind of requests, against which services and what components you are testing and the estimate for the implementation
> 
> @randomorder
> 
> * test ckan is responding -> GET request on the user login page
> * test redis -> GET request with authentication in header with data from environment
> * test solr -> this will be a curl request from the composition as it is in  there now
> * generic authenticated ckan request -> a GET and a POST using apykey
>   This implementation shoulkd be fast as there is no need for deployments to test

Looks good to me. Works for you too @etj ?
