### ISSUE TITLE
Dump info on CKAN forced restart

### ISSUE THREAD

**Issue by etj** [geosolutions-it/C195-azure-workspace#16]
Add to the script implemented for #10 the gdb commands described in #15, in order to have some info on the freezed CKAN instances.

**Comment by randomorder** [comment]
still relevant @etj ?

**Comment by etj** [comment]
@randomorder yes, we did not find the cause of the freeze yet.

**Comment by etj** [comment]
Strange `.txt` file:

```
root@ckan-vmtest3:~# ll /mnt/ckanshare/
total 6
drwxrwxrwx 2 root root    0 Apr  1 15:57 ./
drwxr-xr-x 5 root root 4096 Apr  1 15:57 ../
-rwxrwxrwx 1 root root 1002 Apr  2 14:27 .txt*
-rwxrwxrwx 1 root root 1002 Apr  2 10:11 20210322_gdb_ckan.txt*
drwxrwxrwx 2 root root    0 Apr  1 16:07 storage/
drwxrwxrwx 2 root root    0 Apr  1 16:08 webassets/
root@ckan-vmtest3:~#
```

The file does not include the output of the `gdb` command:
```
root@ckan-vmtest3:~# cat /mnt/ckanshare/20210322_gdb_ckan.txt 
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/ckan/venv/bin/python3...Reading symbols from /usr/lib/debug/.build-id/99/21c75e6930d3e9d9fa8c942aca9dc4500bb65f.debug...done.
done.
Attaching to program: /usr/lib/ckan/venv/bin/python3, process 38
(gdb) (gdb) (gdb) (gdb) (gdb) (gdb) (gdb) quit
root@ckan-vmtest3:~# 
```

**Comment by lpasquali** [comment]
@etj stack trace is working correctly with latest fixes, I tested locally with success, for you to see it "online" I just need to rebuild the image in the test environment, about this, I would suggest a clean deployment from master branch (maybe to be done for future improvements/fixes as an usual test) before giving the modifications to the customer if you and @randomorder agree.
I would save needed ssh keys before re-deployment

**Comment by randomorder** [comment]
yes

**Comment by lpasquali** [comment]
Step 1 the ARM deployment is ok.
Deployment completed with no  errors
![Screenshot from 2021-04-06 15-44-46](https://user-images.githubusercontent.com/1780406/113720571-16467b00-96ef-11eb-98d1-687fcd48162c.png)

**Comment by korotkin** [comment]
Yesterday was sentry logger
ckan.ini:

crudini --set --verbose --list --list-sep=\  ${CONFIG_INI} app:main ckan.plugins sentry_logger
crudini --set --verbose  ${CONFIG_INI} app:main ckanext.sentry_logger.sentry_dsn https://xxxxxx@xxxx.ingest.sentry.io/xxxx
crudini --set --verbose  ${CONFIG_INI} app:main ckanext.sentry_logger.sentry_enable_test_url true



Dockerfile:

RUN $CKAN_VENV/bin/pip install -e git+https://github.com/korotkin/ckanext-sentry-logger.git@main#egg=ckanext-sentry-logger
