### ISSUE TITLE
Bug in AZ prevent solr installation

### ISSUE THREAD

**Issue by etj** [geosolutions-it/C195-azure-workspace#19]
Recent updates in azure repository commands made available the bugged version of `az`:
- https://github.com/Azure/azure-cli/issues/16705
- https://github.com/Azure/azure-cli/issues/16499

This has also been reported on https://github.com/geosolutions-it/C195-azure-workspace/issues/6#issuecomment-810055080

These issues prevent the deploy of the solr container.

We're going to move the solr java app into the VM running CKAN.

**Comment by lpasquali** [comment]
more over @etj since yeatserday 31 March I have experienced one new issue that can be described as this:

- I run the command as mentioned above two times
- first time it fails as per the two bugs above
- second time it never deploys and it gets stuck in a "creating" phase looking at the portal panel

**Comment by randomorder** [comment]
what's the plan to fix it and how long would iut take @lpasquali ?

**Comment by lpasquali** [comment]
> what's the plan to fix it and how long would iut take @lpasquali ?

the plan discussed with @etj is to add it to the ckan vm, this should be pretty quick @randomorder

**Comment by randomorder** [comment]
go ahead and keep us posted in the skype group

**Comment by lpasquali** [comment]
> go ahead and keep us posted in the skype group

I'm close to be done I will soon @randomorder

**Comment by lpasquali** [comment]
PR here @etj https://github.com/geosolutions-it/C195-azure-workspace/pull/21

**Comment by lpasquali** [comment]
@etj can we close this?
