### ISSUE TITLE
Add grace period plugin

### ISSUE THREAD

**Issue by etj** [geosolutions-it/C195-azure-workspace#28]
# Install CKAN extension

New CKAN extension to be deployed:

git clone 
- Repo https://github.com/geosolutions-it/ckanext-grace-period
- Branch `main`

Then

    cd ckanext-grace-period
    pip install -e .

# `ckan.ini` changes

Add plugin `grace_period`

Set items:
- Collaborators:
  ```
  ckan.auth.allow_dataset_collaborators = true
  ```
  This is not specific to this extension, but to CKAN itself:

**Comment by randomorder** [comment]
@lpasquali can you please attach an estimate?

**Comment by lpasquali** [comment]
@randomorder done
