### ISSUE TITLE
Create a monitoring job for CREA production site

### ISSUE THREAD

**Issue by etj** [geosolutions-it/C195-azure-workspace#30]
Need a job in geosolutions monitoring site to perform checks on 
- https://ckananaee4567.westeurope.cloudapp.azure.com/ 
- https://ckananaee2342.westeurope.cloudapp.azure.com/

**Comment by lpasquali** [comment]
@etj I added checks (http checks) in monitoring here:

http://monitoring.geo-solutions.it/resources?lang=en&tag=CREA

**Comment by lpasquali** [comment]
@etj would you like receiving alerts about these http checks?

**Comment by randomorder** [comment]
yes @lpasquali go ahead

**Comment by lpasquali** [comment]
@randomorder done
