### ISSUE TITLE
Disable debug option

### ISSUE THREAD

**Issue by etj** [geosolutions-it/C195-azure-workspace#31]
`debug` should be set to `False` in line
```
crudini --set --verbose ${CONFIG_INI} DEFAULT debug True
```
in file 
https://github.com/geosolutions-it/C195-azure-workspace/blob/master/ckan-docker/ckan-entrypoint.sh#L74

**Comment by lpasquali** [comment]
@randomorder it is one liner, going to add this to my final PR in test
