### ISSUE TITLE
Postgres data persistence

### ISSUE THREAD

**Issue by lpasquali** [geosolutions-it/C195-azure-workspace#4]
we need to check how to persist data if postgres instance on azure is removed

**Comment by randomorder** [comment]
I've made some minor changes to the page @lpasquali 

Please move it under a PostgreSQL global page and add a TOC if possible

**Comment by randomorder** [comment]
please keep us posted about the prorgess and how long it takes close this @lpasquali

**Comment by lpasquali** [comment]
@randomorder sure, here is the progress:

As already supposed there is no way to add any kind of storage onto an Azure managed PostgreSQL instances besides the actual storage that is not possible to "browse or mount in any way".

I implemented provisioning of postges databases and  a toolset of scripts to backup everything on a cronjob basis or on demand and save it on the share mounted on ckan vm, now I'm testing it, everything is parametrized sourcing from the enviroments and there is no need for any knowledge of postgres to run these.

**Comment by lpasquali** [comment]
at the moment deployment provisions and reaches correctly azure managed postgres on the backend network, and is capable to take full backups on demand or by cron, if needed.

**Comment by lpasquali** [comment]
provisioning new databases and backup existing ones is now supported.

**Comment by lpasquali** [comment]
@etj can we close this?
