### ISSUE TITLE
SSL certificates

### ISSUE THREAD

**Issue by etj** [geosolutions-it/C195-azure-workspace#45]
Allow and document the use of the customer's own SSL certificates.

**Comment by lpasquali** [comment]
@etj  I have procedure ready for custom ssl here https://github.com/geosolutions-it/C195-azure-workspace/pull/46
It is a not so simple procedure in my opinion even if I tried to keep as simpler possible but it may be advisable for customer to have our support on the day they put the actual ssl certificate on the vm

**Comment by lpasquali** [comment]
@etj PR updated to full automatic support. customer basically needs just  to alter domain name in env and add certificates in a precise location on the installation machine

**Comment by lpasquali** [comment]
hello @etj are there any news about this PR? https://github.com/geosolutions-it/C195-azure-workspace/pull/46
